services:
  web:
    build:
      context: .
      dockerfile: ./app/dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    container_name: ensys-frontend
    env_file: .env
    restart: always
    volumes:
      - ./app:/app
      - ${LOCAL_DATADIR}:/app/dumps
      - static_volume:/app/cdn_static_root
    networks:
      - backend
      - frontend
    ports:
      - "${DJANGO_PORT}:8000"

  api:
    build:
      context: .
      dockerfile: ./api/dockerfile
    container_name: ensys-backend
    env_file: .env
    restart: always
    volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - ${LOCAL_DATADIR}:/app/data/simulations
    networks:
      - backend

  proxy:
    build: ./proxy
    container_name: gui_proxy
    restart: always
    ports:
        - ${PROXY_PORT}:80
    depends_on:
        - web
    volumes:
        - static_volume:/static
    networks:
        - backend
        - frontend

networks:
  backend:
  frontend:

volumes:
  static_volume:
