services:
  db:
    image: postgres:latest
    container_name: db
    env_file: .env
    restart: always
    volumes:
      - ./data/db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file: .env
    restart: always
    ports:
      - "${PGADMIN_PORT}:80"
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    container_name: ensys
    env_file: .env
    restart: always
    volumes:
      - ./app:/app
    ports:
      - "${DJANGO_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./app
          target: ./app
        - action: rebuild
          path: ./requirements/requirements.txt
        - action: rebuild
          path: .env
    depends_on:
      - db