services:
  db:
    image: postgres
    env_file:
      - path: default.env
        required: true
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    env_file:
      - path: ./default.env
        required: true
    volumes:
      - ./app:/app
    ports:
      - "${DJANGO_PORT}:8000"
    depends_on:
      - db