services:
  db:
    image: postgres
    env_file:
      - path: .env
        required: true
    volumes:
      - ./data/db:/var/lib/postgresql/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file: .env
    volumes:
      - ./app:/app
    ports:
      - "${DJANGO_PORT}:8000"
    develop:
      watch:
        - action: sync
          path: ./app
          target: ./app
          ignore:
            - ""
        - action: rebuild
          path: ./requirements/requirements.txt
        - action: rebuild
          path: .env
    depends_on:
      - db