name: Linter

on: 
  push:
      paths-ignore:
      - 'README.md'
  pull_request:
    branches: 
      -main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v4
    - uses: psf/black@stable
